### ISSUE TITLE
Pointer to image.Image interface

### ISSUE THREAD

**Issue by diamondburned** [buckket/go-blurhash#3]
This library has the Encode API take in a pointer to image.Image (`*image.Image`) instead of either the interface itself (which has an underlying value of a pointer) or a concrete struct such as `*image.NRGBA`. This is usually a bad idea.

The lines that use this "pointer to interface" seem to only dereference the interface and not change it:

https://github.com/buckket/go-blurhash/blob/master/encode.go#L110-L111

```go
height := (*rgba).Bounds().Max.Y
width := (*rgba).Bounds().Max.X
```

https://github.com/buckket/go-blurhash/blob/master/encode.go#L131

```go
rt, gt, bt, _ := (*rgba).At(x, y).RGBA()
```

**Comment by buckket** [comment]
You’re correct. I can’t recall why I’ve chosen *image.Image, it’s not necessary.
